import type { Metadata } from "next";
import HomeClient from "./HomeClient";

export const metadata: Metadata = {
  title: "Private Taxi & Airport Transfer Thailand | Taxi Saver Thailand",
  description:
    "Book a private taxi or VIP Alphard transfer from Suvarnabhumi (BKK) & Don Mueang (DMK) airports to Bangkok, Pattaya, Hua Hin. No deposit required. Best rates guaranteed.",
  keywords: [
    "taxi saver",
    "taxi saver thailand",
    "book taxi thailand",
    "airport transfer bangkok",
    "pattaya taxi transfer",
    "hua hin taxi transfer",
    "bangkok to pattaya taxi",
    "suvarnabhumi airport taxi",
    "don mueang airport taxi",
    "no deposit taxi booking",
    "taxi bkk to pattaya",
    "taxi bangkok to pattaya",
    "taxi bangkok to hua hin",
    "taxi pattaya to bangkok",
    "suvarnabhumi to pattaya taxi",
    "don mueang to pattaya taxi",
    "taxi bkk to hua hin",
    "bangkok airport taxi transfer",
    "private transfer bangkok to pattaya",
    "toyota alphard taxi bangkok",
    "toyota alphard taxi bangkok to pattaya",
    "toyota fortuner taxi thailand",
    "suv taxi bangkok to pattaya",
    "vip van transfer bangkok",
    "luxury van transfer pattaya",
    "sedan taxi bangkok airport",
    "camry taxi bangkok",
    "minivan transfer bangkok",
    "private commuter van bangkok",
    "taxi bangkok airport to pattaya hotel",
    "private transfer don mueang to pattaya",
    "suvarnabhumi to pattaya taxi price",
    "bangkok to hua hin private taxi cost",
    "taxi transfer bangkok to koh chang",
    "taxi bangkok to ban phe pier",
    "bangkok airport to hotel transfer",
    "bkk airport pick up service",
    "dmk airport pick up service",
    "เหมารถไปต่างจังหวัด",
    "เหมารถกรุงเทพไปพัทยา",
    "เหมารถกรุงเทพไปหัวหิน",
    "แท็กซี่สุวรรณภูมิ พัทยา",
    "แท็กซี่ดอนเมือง พัทยา",
    "รถรับส่งสุวรรณภูมิ กรุงเทพ",
    "รถรับส่งสนามบินดอนเมือง",
    "รถตู้นำเที่ยวพัทยา",
    "แท็กซี่กรุงเทพไปชลบุรี",
    "เหมารถไปท่าเรือบ้านเพ",
    "รถตู้อัลพาร์ด สุวรรณภูมิ",
    "เหมารถตู้อัลพาร์ด",
    "จองรถตู้ vip พัทยา",
    "รถตู้อัลพาร์ดไปพัทยา",
    "รถฟอร์จูนเนอร์เหมาไปพัทยา",
    "รถตู้นำเที่ยวหัวหิน",
    "เหมารถตู้ commuter กรุงเทพ",
    "บริการแท็กซี่ 24 ชั่วโมง",
    "จองรถออนไลน์ ไม่มีมัดจำ",
    "บริการรถรับส่งสนามบินสุวรรณภูมิไปพัทยา ราคา",
    "รถเหมาจากพัทยาไปกรุงเทพ",
    "จองรถข้ามจังหวัด พัทยา หัวหิน",
    "เหมารถตู้อัลพาร์ด กทม"
  ],
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: "Taxi Saver Thailand | Private Taxi Service & Airport Transfer",
    description: "Affordable private taxi service and airport transfers in Thailand. Book rides from Suvarnabhumi (BKK) and Don Mueang (DMK) to Bangkok, Pattaya, Hua Hin. No deposit required, pay the driver directly.",
    url: "https://taxisaverthailand.com",
    siteName: "Taxi Saver Thailand",
    images: [
      {
        url: "/images/og-share.jpg",
        width: 1200,
        height: 675,
        alt: "Taxi Saver Thailand - Private Taxi & Airport Transfer Service",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Taxi Saver Thailand | Private Taxi & Airport Transfer",
    description: "Affordable private taxi service and airport transfers in Thailand. Book rides from Suvarnabhumi (BKK) and Don Mueang (DMK) to Bangkok, Pattaya, Hua Hin. No deposit required, pay the driver directly.",
    images: ["/images/og-share.jpg"],
  },
};

export default function Home() {
  return <HomeClient />;
}
